/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/

var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// main.ts
var main_exports = {};
__export(main_exports, {
  default: () => AutoCorrectPlugin
});
module.exports = __toCommonJS(main_exports);
var import_obsidian = require("obsidian");
var AutoCorrectPlugin = class extends import_obsidian.Plugin {
  async onload() {
    console.log("Loading AutoCorrectPlugin");
    this.registerEvent(
      this.app.workspace.on("editor-change", (editor) => {
        const doc = editor.getDoc();
        const cursor = doc.getCursor();
        const line = doc.getLine(cursor.line);
        const words = line.split(" ");
        const lastChar = line[cursor.ch - 1];
        const punctuation = [" ", ".", ",", ";", ":", "!", "?", "\n"];
        if (punctuation.includes(lastChar)) {
          const lastWordIndex = words.length - 2;
          const lastWord = words[lastWordIndex];
          if (lastWord && lastWord.length > 2 && lastWord[0] === lastWord[0].toUpperCase() && lastWord[1] === lastWord[1].toUpperCase() && lastWord.slice(2).toLowerCase() === lastWord.slice(2)) {
            const correctedWord = lastWord[0] + lastWord.slice(1).toLowerCase();
            words[lastWordIndex] = correctedWord;
            doc.replaceRange(words.join(" "), { line: cursor.line, ch: 0 }, { line: cursor.line, ch: line.length });
          }
        }
      })
    );
  }
  onunload() {
    console.log("Unloading AutoCorrectPlugin");
  }
};
